from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from latest_day_data import request_latest_data
from plot_data import *
from coqt_about import Ui_about_window
from coqt_invalid import Ui_Invalid_Window
from coqt_news import *
import urllib.request
from os import *
import os


class Ui_MainWindow(object):

    def get_data(self):

        self.c_code = self.code.toPlainText()
        latest_data = request_latest_data(self.c_code)

        self.label_total_cases.setText("Total Cases:     " + str(latest_data[0]))
        self.label_total_recoveries.setText("Total Recoveries:     " + str(latest_data[1]))
        self.label_total_deaths.setText("Total Deaths:     " + str(latest_data[2]))
        self.label_total_active.setText("Total Active:     " + str(latest_data[3]))
        self.label_cases_per_1m.setText("Cases Per 1M Population:     " + str(latest_data[4]))
        self.label_deaths_per_1m.setText("Deaths Per 1M Population:     " + str(latest_data[5]))
        self.label_total_tests.setText("Total Tests Conducted:     " + str(latest_data[6]))
        self.label_tests_per_1m.setText("Tests Per 1M Population:     " + str(latest_data[7]))
        self.label_country.setText("Country:     " + str(latest_data[8]))

        if not path.exists("temp"):
            os.mkdir('temp')

        if latest_data[9] == '0':
            self.invalid_window_popup()
            self.country_flag.setPixmap(QtGui.QPixmap("temp/flag_transparent.png"))

        else:
            full_path = 'temp/' + 'flag' + '.png'
            urllib.request.urlretrieve(latest_data[9], full_path)
            self.country_flag.setPixmap(QtGui.QPixmap("temp/flag.png"))

    def invalid_window_popup(self):
        self.InvalidWindow = QtWidgets.QMainWindow()
        self.ui_invalid = Ui_Invalid_Window()
        self.ui_invalid.setupUi_invalid(self.InvalidWindow)
        self.InvalidWindow.show()

    def get_world_data(self):
        self.latest_data = request_latest_data('world')

    def get_plots(self):

        self.c_code = self.code.toPlainText()
        latest_plot_data = request_plots(self.c_code)

        if latest_plot_data[0] == '0':
            self.invalid_window_popup()
            pass

        else:
            totalcases = latest_plot_data[0]
            totalrecovery = latest_plot_data[1]
            totaldeaths = latest_plot_data[2]
            dailycases = latest_plot_data[3]
            dailydeaths = latest_plot_data[4]
            dates = latest_plot_data[5]
            country_name = latest_plot_data[6]

            if self.total_cases_box.isChecked():
                plt.figure('Total Cases', figsize=(7, 7))
                plt.plot(dates, totalcases)
                plt.title('Graph of total cases in ' + country_name)
                plt.xlabel('Dates')
                plt.ylabel('Cases')
                plt.grid(True)
                plt.xticks(rotation=20)

            if self.total_recoveries_box.isChecked():
                plt.figure('Total Recovery', figsize=(7, 7))
                plt.plot(dates[0:len(totalrecovery)], totalrecovery)
                plt.title('Graph of total recovery in ' + country_name)
                plt.xlabel('Dates')
                plt.ylabel('Recoveries')
                plt.grid(True)
                plt.xticks(rotation=20)

            if self.total_deaths_box.isChecked():
                plt.figure('Total Deaths', figsize=(7, 7))
                plt.plot(dates, totaldeaths)
                plt.title('Graph of total deaths in ' + country_name)
                plt.xlabel('Dates')
                plt.ylabel('Deaths')
                plt.grid(True)
                plt.xticks(rotation=20)

            if self.daily_cases_box.isChecked():
                plt.figure('Daily Cases', figsize=(7, 7))
                plt.bar(dates, dailycases)
                plt.title('Graph of daily cases in ' + country_name)
                plt.xlabel('Dates')
                plt.ylabel('Cases')
                plt.grid(True)
                plt.xticks(rotation=20)

            if self.daily_deaths_box.isChecked():
                plt.figure('Daily Deaths', figsize=(7, 7))
                plt.bar(dates, dailydeaths)
                plt.title('Graph of daily deaths in ' + country_name)
                plt.xlabel('Dates')
                plt.ylabel('Deaths')
                plt.grid(True)
                plt.xticks(rotation=20)

            plt.show()

    def open_about_window(self):
        self.AboutWindow = QtWidgets.QMainWindow()
        self.ui_about = Ui_about_window()
        self.ui_about.setupUi_about(self.AboutWindow)
        self.AboutWindow.show()

    def get_covid_news(self):
        latest_news = request_covid_news_title_description()
        latest_news_url = request_covid_news_url()

        url = []
        j = 0

        for i in range(10):
            url.append('<a href=\"' + latest_news_url[i] + '\">' + latest_news[j] + '</a>')
            j += 2

        self.label_news_title1.setText(url[0])
        self.label_news_title2.setText(url[1])
        self.label_news_title3.setText(url[2])
        self.label_news_title4.setText(url[3])
        self.label_news_title5.setText(url[4])
        self.label_news_title6.setText(url[5])
        self.label_news_title7.setText(url[6])
        self.label_news_title8.setText(url[7])
        self.label_news_title9.setText(url[8])
        self.label_news_title10.setText(url[9])

        self.label_news_description1.setText(latest_news[1])
        self.label_news_description2.setText(latest_news[3])
        self.label_news_description3.setText(latest_news[5])
        self.label_news_description4.setText(latest_news[7])
        self.label_news_description5.setText(latest_news[9])
        self.label_news_description6.setText(latest_news[11])
        self.label_news_description7.setText(latest_news[13])
        self.label_news_description8.setText(latest_news[15])
        self.label_news_description9.setText(latest_news[17])
        self.label_news_description10.setText(latest_news[19])

    def setupUi(self, MainWindow):

        self.latest_data = request_latest_data('world')
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1321, 545)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_enter_country_name = QtWidgets.QLabel(self.centralwidget)
        self.label_enter_country_name.setGeometry(QtCore.QRect(20, 140, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_enter_country_name.setFont(font)
        self.label_enter_country_name.setStyleSheet("")
        self.label_enter_country_name.setObjectName("label_enter_country_name")
        self.code = QtWidgets.QTextEdit(self.centralwidget)
        self.code.setEnabled(True)
        self.code.setGeometry(QtCore.QRect(280, 140, 104, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.code.setFont(font)
        self.code.setStyleSheet("")
        self.code.setObjectName("code")
        self.get_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_data_button.setGeometry(QtCore.QRect(280, 180, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.get_data_button.setFont(font)
        self.get_data_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_data_button.setStyleSheet("")
        self.get_data_button.setObjectName("get_data_button")
        self.label_plots_of = QtWidgets.QLabel(self.centralwidget)
        self.label_plots_of.setGeometry(QtCore.QRect(130, 270, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_plots_of.setFont(font)
        self.label_plots_of.setStyleSheet("")
        self.label_plots_of.setObjectName("label_plots_of")
        self.total_cases_box = QtWidgets.QCheckBox(self.centralwidget)
        self.total_cases_box.setGeometry(QtCore.QRect(280, 273, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.total_cases_box.setFont(font)
        self.total_cases_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.total_cases_box.setStyleSheet("")
        self.total_cases_box.setObjectName("total_cases_box")
        self.total_recoveries_box = QtWidgets.QCheckBox(self.centralwidget)
        self.total_recoveries_box.setGeometry(QtCore.QRect(280, 303, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.total_recoveries_box.setFont(font)
        self.total_recoveries_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.total_recoveries_box.setStyleSheet("")
        self.total_recoveries_box.setObjectName("total_recoveries_box")
        self.total_deaths_box = QtWidgets.QCheckBox(self.centralwidget)
        self.total_deaths_box.setGeometry(QtCore.QRect(280, 333, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.total_deaths_box.setFont(font)
        self.total_deaths_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.total_deaths_box.setStyleSheet("")
        self.total_deaths_box.setObjectName("total_deaths_box")
        self.daily_cases_box = QtWidgets.QCheckBox(self.centralwidget)
        self.daily_cases_box.setGeometry(QtCore.QRect(280, 359, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.daily_cases_box.setFont(font)
        self.daily_cases_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.daily_cases_box.setStyleSheet("")
        self.daily_cases_box.setObjectName("daily_cases_box")
        self.get_plots_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_plots_button.setGeometry(QtCore.QRect(280, 440, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.get_plots_button.setFont(font)
        self.get_plots_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_plots_button.setStyleSheet("")
        self.get_plots_button.setFlat(False)
        self.get_plots_button.setObjectName("get_plots_button")
        self.label_total_cases = QtWidgets.QLabel(self.centralwidget)
        self.label_total_cases.setGeometry(QtCore.QRect(470, 240, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_total_cases.setFont(font)
        self.label_total_cases.setStyleSheet("")
        self.label_total_cases.setObjectName("label_total_cases")
        self.label_total_recoveries = QtWidgets.QLabel(self.centralwidget)
        self.label_total_recoveries.setGeometry(QtCore.QRect(470, 270, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_total_recoveries.setFont(font)
        self.label_total_recoveries.setStyleSheet("")
        self.label_total_recoveries.setObjectName("label_total_recoveries")
        self.label_total_deaths = QtWidgets.QLabel(self.centralwidget)
        self.label_total_deaths.setGeometry(QtCore.QRect(470, 300, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_total_deaths.setFont(font)
        self.label_total_deaths.setStyleSheet("")
        self.label_total_deaths.setObjectName("label_total_deaths")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1230, 520, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.label_total_active = QtWidgets.QLabel(self.centralwidget)
        self.label_total_active.setGeometry(QtCore.QRect(470, 330, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_total_active.setFont(font)
        self.label_total_active.setStyleSheet("")
        self.label_total_active.setObjectName("label_total_active")
        self.label_cases_per_1m = QtWidgets.QLabel(self.centralwidget)
        self.label_cases_per_1m.setGeometry(QtCore.QRect(470, 356, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_cases_per_1m.setFont(font)
        self.label_cases_per_1m.setStyleSheet("")
        self.label_cases_per_1m.setObjectName("label_cases_per_1m")
        self.label_deaths_per_1m = QtWidgets.QLabel(self.centralwidget)
        self.label_deaths_per_1m.setGeometry(QtCore.QRect(470, 390, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_deaths_per_1m.setFont(font)
        self.label_deaths_per_1m.setStyleSheet("")
        self.label_deaths_per_1m.setObjectName("label_deaths_per_1m")
        self.label_total_tests = QtWidgets.QLabel(self.centralwidget)
        self.label_total_tests.setGeometry(QtCore.QRect(470, 420, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_total_tests.setFont(font)
        self.label_total_tests.setStyleSheet("")
        self.label_total_tests.setObjectName("label_total_tests")
        self.label_tests_per_1m = QtWidgets.QLabel(self.centralwidget)
        self.label_tests_per_1m.setGeometry(QtCore.QRect(470, 445, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_tests_per_1m.setFont(font)
        self.label_tests_per_1m.setStyleSheet("")
        self.label_tests_per_1m.setObjectName("label_tests_per_1m")
        self.label_country = QtWidgets.QLabel(self.centralwidget)
        self.label_country.setGeometry(QtCore.QRect(470, 210, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_country.setFont(font)
        self.label_country.setStyleSheet("")
        self.label_country.setObjectName("label_country")
        self.daily_deaths_box = QtWidgets.QCheckBox(self.centralwidget)
        self.daily_deaths_box.setGeometry(QtCore.QRect(280, 390, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.daily_deaths_box.setFont(font)
        self.daily_deaths_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.daily_deaths_box.setStyleSheet("")
        self.daily_deaths_box.setObjectName("daily_deaths_box")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setEnabled(True)
        self.line_2.setGeometry(QtCore.QRect(0, 500, 1311, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("")
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 520, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 20, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_world_infected = QtWidgets.QLabel(self.frame)
        self.label_world_infected.setGeometry(QtCore.QRect(0, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_world_infected.setFont(font)
        self.label_world_infected.setStyleSheet("")
        self.label_world_infected.setAlignment(QtCore.Qt.AlignCenter)
        self.label_world_infected.setObjectName("label_world_infected")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label_world_infected.raise_()
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(240, 20, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(False)
        font.setWeight(50)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_world_dead = QtWidgets.QLabel(self.frame_2)
        self.label_world_dead.setGeometry(QtCore.QRect(0, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_world_dead.setFont(font)
        self.label_world_dead.setStyleSheet("")
        self.label_world_dead.setAlignment(QtCore.Qt.AlignCenter)
        self.label_world_dead.setObjectName("label_world_dead")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(0, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(440, 20, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(False)
        font.setWeight(50)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_world_recovered = QtWidgets.QLabel(self.frame_3)
        self.label_world_recovered.setGeometry(QtCore.QRect(0, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_world_recovered.setFont(font)
        self.label_world_recovered.setStyleSheet("")
        self.label_world_recovered.setAlignment(QtCore.Qt.AlignCenter)
        self.label_world_recovered.setObjectName("label_world_recovered")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(0, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 120, 741, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_plots_of_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_plots_of_2.setGeometry(QtCore.QRect(10, 480, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_plots_of_2.setFont(font)
        self.label_plots_of_2.setStyleSheet("")
        self.label_plots_of_2.setObjectName("label_plots_of_2")
        self.about_button = QtWidgets.QPushButton(self.centralwidget)
        self.about_button.setGeometry(QtCore.QRect(0, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.about_button.setFont(font)
        self.about_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about_button.setStyleSheet("")
        self.about_button.setObjectName("about_button")
        self.country_flag = QtWidgets.QLabel(self.centralwidget)
        self.country_flag.setGeometry(QtCore.QRect(550, 140, 100, 60))
        self.country_flag.setStyleSheet("")
        self.country_flag.setText("")
        self.country_flag.setPixmap(QtGui.QPixmap(":/images/images/flag_transparent.png"))
        self.country_flag.setScaledContents(True)
        self.country_flag.setAlignment(QtCore.Qt.AlignCenter)
        self.country_flag.setWordWrap(False)
        self.country_flag.setObjectName("country_flag")
        self.label_plots_of_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_plots_of_3.setGeometry(QtCore.QRect(10, 440, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_plots_of_3.setFont(font)
        self.label_plots_of_3.setStyleSheet("")
        self.label_plots_of_3.setObjectName("label_plots_of_3")
        self.label_plots_of_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_plots_of_4.setGeometry(QtCore.QRect(20, 460, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_plots_of_4.setFont(font)
        self.label_plots_of_4.setStyleSheet("")
        self.label_plots_of_4.setObjectName("label_plots_of_4")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(740, -2, 581, 512))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 562, 1188))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_news_title1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title1.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title1.setFont(font)
        self.label_news_title1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title1.setStyleSheet("")
        self.label_news_title1.setOpenExternalLinks(True)
        self.label_news_title1.setObjectName("label_news_title1")
        self.verticalLayout.addWidget(self.label_news_title1)
        self.label_news_description1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description1.sizePolicy().hasHeightForWidth())
        self.label_news_description1.setSizePolicy(sizePolicy)
        self.label_news_description1.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description1.setStyleSheet("")
        self.label_news_description1.setWordWrap(True)
        self.label_news_description1.setObjectName("label_news_description1")
        self.verticalLayout.addWidget(self.label_news_description1)
        self.label_news_title2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title2.setFont(font)
        self.label_news_title2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title2.setStyleSheet("")
        self.label_news_title2.setOpenExternalLinks(True)
        self.label_news_title2.setObjectName("label_news_title2")
        self.verticalLayout.addWidget(self.label_news_title2)
        self.label_news_description2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description2.sizePolicy().hasHeightForWidth())
        self.label_news_description2.setSizePolicy(sizePolicy)
        self.label_news_description2.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description2.setStyleSheet("")
        self.label_news_description2.setWordWrap(True)
        self.label_news_description2.setObjectName("label_news_description2")
        self.verticalLayout.addWidget(self.label_news_description2)
        self.label_news_title3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title3.setFont(font)
        self.label_news_title3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title3.setStyleSheet("")
        self.label_news_title3.setOpenExternalLinks(True)
        self.label_news_title3.setObjectName("label_news_title3")
        self.verticalLayout.addWidget(self.label_news_title3)
        self.label_news_description3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description3.sizePolicy().hasHeightForWidth())
        self.label_news_description3.setSizePolicy(sizePolicy)
        self.label_news_description3.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description3.setStyleSheet("")
        self.label_news_description3.setWordWrap(True)
        self.label_news_description3.setObjectName("label_news_description3")
        self.verticalLayout.addWidget(self.label_news_description3)
        self.label_news_title4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title4.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title4.setFont(font)
        self.label_news_title4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title4.setStyleSheet("")
        self.label_news_title4.setOpenExternalLinks(True)
        self.label_news_title4.setObjectName("label_news_title4")
        self.verticalLayout.addWidget(self.label_news_title4)
        self.label_news_description4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description4.sizePolicy().hasHeightForWidth())
        self.label_news_description4.setSizePolicy(sizePolicy)
        self.label_news_description4.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description4.setStyleSheet("")
        self.label_news_description4.setWordWrap(True)
        self.label_news_description4.setObjectName("label_news_description4")
        self.verticalLayout.addWidget(self.label_news_description4)
        self.label_news_title5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title5.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title5.setFont(font)
        self.label_news_title5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title5.setStyleSheet("")
        self.label_news_title5.setOpenExternalLinks(True)
        self.label_news_title5.setObjectName("label_news_title5")
        self.verticalLayout.addWidget(self.label_news_title5)
        self.label_news_description5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description5.sizePolicy().hasHeightForWidth())
        self.label_news_description5.setSizePolicy(sizePolicy)
        self.label_news_description5.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description5.setStyleSheet("")
        self.label_news_description5.setWordWrap(True)
        self.label_news_description5.setObjectName("label_news_description5")
        self.verticalLayout.addWidget(self.label_news_description5)
        self.label_news_title6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title6.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title6.setFont(font)
        self.label_news_title6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title6.setStyleSheet("")
        self.label_news_title6.setOpenExternalLinks(True)
        self.label_news_title6.setObjectName("label_news_title6")
        self.verticalLayout.addWidget(self.label_news_title6)
        self.label_news_description6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description6.sizePolicy().hasHeightForWidth())
        self.label_news_description6.setSizePolicy(sizePolicy)
        self.label_news_description6.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description6.setStyleSheet("")
        self.label_news_description6.setWordWrap(True)
        self.label_news_description6.setObjectName("label_news_description6")
        self.verticalLayout.addWidget(self.label_news_description6)
        self.label_news_title7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title7.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title7.setFont(font)
        self.label_news_title7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title7.setStyleSheet("")
        self.label_news_title7.setOpenExternalLinks(True)
        self.label_news_title7.setObjectName("label_news_title7")
        self.verticalLayout.addWidget(self.label_news_title7)
        self.label_news_description7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description7.sizePolicy().hasHeightForWidth())
        self.label_news_description7.setSizePolicy(sizePolicy)
        self.label_news_description7.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description7.setStyleSheet("")
        self.label_news_description7.setWordWrap(True)
        self.label_news_description7.setObjectName("label_news_description7")
        self.verticalLayout.addWidget(self.label_news_description7)
        self.label_news_title8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title8.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title8.setFont(font)
        self.label_news_title8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title8.setStyleSheet("")
        self.label_news_title8.setOpenExternalLinks(True)
        self.label_news_title8.setObjectName("label_news_title8")
        self.verticalLayout.addWidget(self.label_news_title8)
        self.label_news_description8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description8.sizePolicy().hasHeightForWidth())
        self.label_news_description8.setSizePolicy(sizePolicy)
        self.label_news_description8.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description8.setStyleSheet("")
        self.label_news_description8.setWordWrap(True)
        self.label_news_description8.setObjectName("label_news_description8")
        self.verticalLayout.addWidget(self.label_news_description8)
        self.label_news_title9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title9.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title9.setFont(font)
        self.label_news_title9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title9.setStyleSheet("")
        self.label_news_title9.setOpenExternalLinks(True)
        self.label_news_title9.setObjectName("label_news_title9")
        self.verticalLayout.addWidget(self.label_news_title9)
        self.label_news_description9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description9.sizePolicy().hasHeightForWidth())
        self.label_news_description9.setSizePolicy(sizePolicy)
        self.label_news_description9.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description9.setStyleSheet("")
        self.label_news_description9.setWordWrap(True)
        self.label_news_description9.setObjectName("label_news_description9")
        self.verticalLayout.addWidget(self.label_news_description9)
        self.label_news_title10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_news_title10.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_news_title10.setFont(font)
        self.label_news_title10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_news_title10.setStyleSheet("")
        self.label_news_title10.setOpenExternalLinks(True)
        self.label_news_title10.setObjectName("label_news_title10")
        self.verticalLayout.addWidget(self.label_news_title10)
        self.label_news_description10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_news_description10.sizePolicy().hasHeightForWidth())
        self.label_news_description10.setSizePolicy(sizePolicy)
        self.label_news_description10.setMinimumSize(QtCore.QSize(0, 75))
        self.label_news_description10.setStyleSheet("")
        self.label_news_description10.setWordWrap(True)
        self.label_news_description10.setObjectName("label_news_description10")
        self.verticalLayout.addWidget(self.label_news_description10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea.raise_()
        self.label_enter_country_name.raise_()
        self.code.raise_()
        self.get_data_button.raise_()
        self.label_plots_of.raise_()
        self.total_cases_box.raise_()
        self.total_recoveries_box.raise_()
        self.total_deaths_box.raise_()
        self.daily_cases_box.raise_()
        self.get_plots_button.raise_()
        self.label_total_cases.raise_()
        self.label_total_recoveries.raise_()
        self.label_total_deaths.raise_()
        self.label_6.raise_()
        self.label_total_active.raise_()
        self.label_cases_per_1m.raise_()
        self.label_deaths_per_1m.raise_()
        self.label_total_tests.raise_()
        self.label_tests_per_1m.raise_()
        self.label_country.raise_()
        self.daily_deaths_box.raise_()
        self.line_2.raise_()
        self.label_2.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.line_3.raise_()
        self.frame.raise_()
        self.label_plots_of_2.raise_()
        self.country_flag.raise_()
        self.label_plots_of_3.raise_()
        self.label_plots_of_4.raise_()
        self.about_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave_Ctrl_S = QtWidgets.QAction(MainWindow)
        self.actionSave_Ctrl_S.setObjectName("actionSave_Ctrl_S")
        self.actionSave_As_Ctrl_Shift_S = QtWidgets.QAction(MainWindow)
        self.actionSave_As_Ctrl_Shift_S.setObjectName("actionSave_As_Ctrl_Shift_S")
        self.actionNew_Ctrl_N = QtWidgets.QAction(MainWindow)
        self.actionNew_Ctrl_N.setObjectName("actionNew_Ctrl_N")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.get_covid_news()
        self.get_data_button.clicked.connect(self.get_data)
        self.get_plots_button.clicked.connect(self.get_plots)
        self.about_button.clicked.connect(self.open_about_window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COVID-19 Desktop Tracker v1.1"))
        self.label_enter_country_name.setText(_translate("MainWindow", "Enter Country Name or Code:"))
        self.get_data_button.setText(_translate("MainWindow", "Get Data*"))
        self.label_plots_of.setText(_translate("MainWindow", "Plot graphs of:"))
        self.total_cases_box.setText(_translate("MainWindow", "Total Cases"))
        self.total_recoveries_box.setText(_translate("MainWindow", "Total Recoveries"))
        self.total_deaths_box.setText(_translate("MainWindow", "Total Deaths"))
        self.daily_cases_box.setText(_translate("MainWindow", "Daily Cases"))
        self.get_plots_button.setText(_translate("MainWindow", "Get Plots**"))
        self.label_total_cases.setText(_translate("MainWindow", "Total Cases:"))
        self.label_total_recoveries.setText(_translate("MainWindow", "Total Recoveries:"))
        self.label_total_deaths.setText(_translate("MainWindow", "Total Deaths:"))
        self.label_6.setText(_translate("MainWindow", "© Rahul Shagrithaya"))
        self.label_total_active.setText(_translate("MainWindow", "Total Active:"))
        self.label_cases_per_1m.setText(_translate("MainWindow", "Cases Per 1M Population:"))
        self.label_deaths_per_1m.setText(_translate("MainWindow", "Deaths Per 1M Population:"))
        self.label_total_tests.setText(_translate("MainWindow", "Total Tests Conducted:"))
        self.label_tests_per_1m.setText(_translate("MainWindow", "Tests Per 1M Population:"))
        self.label_country.setText(_translate("MainWindow", "Country:"))
        self.daily_deaths_box.setText(_translate("MainWindow", "Daily Deaths"))
        self.label_2.setText(_translate("MainWindow", "https://github.com/RahulShagri"))
        self.label_world_infected.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "infected"))
        self.label_world_dead.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "dead"))
        self.label_world_recovered.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "recovered"))
        self.label_plots_of_2.setText(_translate("MainWindow", "** Plot data is updated on daily basis."))
        self.about_button.setText(_translate("MainWindow", "About"))
        self.label_plots_of_3.setText(_translate("MainWindow", "*  Data may differ from plot data. "))
        self.label_plots_of_4.setText(_translate("MainWindow", "This data is updated live."))
        self.label.setText(_translate("MainWindow", "News Related to Coronavirus"))
        self.label_news_title1.setText(_translate("MainWindow", "News Title"))
        self.label_news_description1.setText(_translate("MainWindow", "News Description"))
        self.label_news_title2.setText(_translate("MainWindow", "News Title"))
        self.label_news_description2.setText(_translate("MainWindow", "News Description"))
        self.label_news_title3.setText(_translate("MainWindow", "News Title"))
        self.label_news_description3.setText(_translate("MainWindow", "News Description"))
        self.label_news_title4.setText(_translate("MainWindow", "News Title"))
        self.label_news_description4.setText(_translate("MainWindow", "News Description"))
        self.label_news_title5.setText(_translate("MainWindow", "News Title"))
        self.label_news_description5.setText(_translate("MainWindow", "News Description"))
        self.label_news_title6.setText(_translate("MainWindow", "News Title"))
        self.label_news_description6.setText(_translate("MainWindow", "News Description"))
        self.label_news_title7.setText(_translate("MainWindow", "News Title"))
        self.label_news_description7.setText(_translate("MainWindow", "News Description"))
        self.label_news_title8.setText(_translate("MainWindow", "News Title"))
        self.label_news_description8.setText(_translate("MainWindow", "News Description"))
        self.label_news_title9.setText(_translate("MainWindow", "News Title"))
        self.label_news_description9.setText(_translate("MainWindow", "News Description"))
        self.label_news_title10.setText(_translate("MainWindow", "News Title"))
        self.label_news_description10.setText(_translate("MainWindow", "News Description"))
        self.actionSave_Ctrl_S.setText(_translate("MainWindow", "Save Ctrl+S"))
        self.actionSave_As_Ctrl_Shift_S.setText(_translate("MainWindow", "Save As Ctrl+Shift+S"))
        self.actionNew_Ctrl_N.setText(_translate("MainWindow", "New Ctrl+N"))

        self.label_world_infected.setText(_translate("MainWindow", str(self.latest_data[0])))
        self.label_world_dead.setText(_translate("MainWindow", str(self.latest_data[2])))
        self.label_world_recovered.setText(_translate("MainWindow", str(self.latest_data[1])))


import resources_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
